// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB170QBspDa2SBmO8U2ih3SJ_6n0VW7BnA',
    appId: '1:864803699557:web:7a9a364aa0dde7613f7f8c',
    messagingSenderId: '864803699557',
    projectId: 'flutter-application-24fea',
    authDomain: 'flutter-application-24fea.firebaseapp.com',
    storageBucket: 'flutter-application-24fea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFbE8sZV7_yYI0EwD47J6V44Fi5RIv6uE',
    appId: '1:864803699557:android:220f61f2cc8abd1a3f7f8c',
    messagingSenderId: '864803699557',
    projectId: 'flutter-application-24fea',
    storageBucket: 'flutter-application-24fea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtU9wXG0XgjKgP3hYBKsIiZVOFrLzobrM',
    appId: '1:864803699557:ios:355c9b6853c92c8a3f7f8c',
    messagingSenderId: '864803699557',
    projectId: 'flutter-application-24fea',
    storageBucket: 'flutter-application-24fea.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );
}
